local util = require("wowharness.util")

describe("util", function()
  it("splits and trims strings", function()
    assert.are.same({ "a", "b", "c" }, util.split("a,b,c", ","))
    assert.are.equal("x", util.trim("  x\t\n"))
    assert.is_true(util.startsWith("prefix-value", "prefix"))
  end)

  it("normalises windows style paths", function()
    assert.are.equal("UI/Widgets.lua", util.normalizePath("UI\\Widgets.lua"))
    assert.are.equal("a/c", util.normalizePath("a/b/../c"))
    assert.are.equal("a/b", util.normalizePath("./a/./b"))
  end)

  it("joins, splits and inspects paths", function()
    assert.are.equal("base/child.lua", util.joinPath("base", "child.lua"))
    assert.are.equal("base", util.dirname("base/child.lua"))
    assert.are.equal("child.lua", util.basename("base/child.lua"))
  end)

  it("detects files and directories", function()
    assert.is_true(util.fileExists("spec/fixtures/SampleAddon/SampleAddon.toc"))
    assert.is_false(util.fileExists("spec/fixtures/nope.toc"))
    assert.is_true(util.isDirectory("spec/fixtures/SampleAddon"))
    assert.is_false(util.isDirectory("spec/fixtures/SampleAddon/Core.lua"))
  end)

  it("resolves toc paths ignoring case", function()
    local resolved = util.resolveCaseInsensitive("spec/fixtures/SampleAddon", "core.LUA")
    assert.are.equal("spec/fixtures/SampleAddon/Core.lua", resolved)
    assert.is_nil(util.resolveCaseInsensitive("spec/fixtures/SampleAddon", "nope.lua"))
  end)

  it("reads files", function()
    assert.is_truthy(string.find(util.readFile("spec/fixtures/XmlAddon/Loaded.lua"), "XmlAddonLoaded"))
    assert.is_nil(util.readFile("spec/fixtures/missing"))
  end)
end)
