#!/usr/bin/env lua
--- Amalgamate the harness into a single portable `wowtest.lua` script.
--
-- The bundle runs on any Lua 5.1+ interpreter with no rocks installed, which
-- is what we ship for platforms we do not build a native binary for.
-- Usage: lua scripts/build-bundle.lua [output-file]

local MODULES = {
  "wowharness",
  "wowharness.api.chat",
  "wowharness.api.events",
  "wowharness.api.frames",
  "wowharness.api.game",
  "wowharness.api.savedvariables",
  "wowharness.api.timers",
  "wowharness.cli",
  "wowharness.context",
  "wowharness.environment",
  "wowharness.loader",
  "wowharness.profile",
  "wowharness.report",
  "wowharness.runner",
  "wowharness.session",
  "wowharness.toc",
  "wowharness.util",
  "wowharness.version",
}

local function scriptDirectory()
  return string.match(arg[0] or "", "^(.*)[/\\][^/\\]*$") or "."
end

local function modulePath(moduleName)
  local relative = string.gsub(moduleName, "%.", "/")
  local root = scriptDirectory() .. "/../src/"
  local candidates = { root .. relative .. ".lua", root .. relative .. "/init.lua" }
  for _, candidate in ipairs(candidates) do
    local handle = io.open(candidate, "r")
    if handle then
      handle:close()
      return candidate
    end
  end
  error("cannot find source for module " .. moduleName)
end

local function readFile(path)
  local handle = assert(io.open(path, "rb"))
  local contents = handle:read("*a")
  handle:close()
  return contents
end

local outputPath = arg[1] or (scriptDirectory() .. "/../dist/wowtest.lua")

local pieces = {
  "#!/usr/bin/env lua\n",
  "-- wowtest: self contained World of Warcraft addon smoke tester.\n",
  "-- Generated by scripts/build-bundle.lua; do not edit by hand.\n",
}

for _, moduleName in ipairs(MODULES) do
  local source = readFile(modulePath(moduleName))
  table.insert(pieces, string.format(
    "package.preload[%q] = function(...)\n%s\nend\n",
    moduleName,
    source
  ))
end

table.insert(pieces, "os.exit(require('wowharness.cli').main(arg or {}))\n")

local outHandle = assert(io.open(outputPath, "w"))
outHandle:write(table.concat(pieces))
outHandle:close()
print("wrote " .. outputPath)
